name: .NET Desktop

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    runs-on: windows-latest

    env:
      Solution_Name: AsusFanControl.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Cache NuGet packages
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    # Execute all unit tests in the solution
    # (Optional: Add test step if there are tests)

    # Build the application
    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

    # Download PsExec and Create Batch Script
    - name: Prepare Artifacts
      run: |
        Invoke-WebRequest -Uri "https://download.sysinternals.com/files/PSTools.zip" -OutFile "PSTools.zip"
        Expand-Archive -Path "PSTools.zip" -DestinationPath "PSTools"
        Copy-Item -Path "PSTools/PsExec.exe" -Destination "bin/${{ matrix.platform }}/${{ matrix.configuration }}/"

        $batContent = @"
        net session >nul 2>&1
        if %ERRORLEVEL% NEQ 0 (
            echo Requesting administrative privileges...
            powershell -Command "Start-Process -FilePath 'cmd.exe' -ArgumentList '/c \"\"%~f0\"\"' -Verb RunAs"
            exit /b
        )

        "%~dp0PsExec" -i -s -d "%~dp0AsusFanControlGUI.exe"
        "@
        $batContent | Out-File -FilePath "bin/${{ matrix.platform }}/${{ matrix.configuration }}/RunAsAdmin.bat" -Encoding ASCII

    # Upload the build artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AsusFanControlGUI
        path: bin/${{ matrix.platform }}/${{ matrix.configuration }}
